README.md
Just a tiny update on the readme.
=> Tiny  readme if people want to contribute

source/schema.md
=> Hidden form field description

source/email.md
This would have been helpful to us so thought we'd pass it along.
=> Directions on modifying newsletters

README.md, _config.yml, source/CNAME, source/deployment.md, source/index.md, source/internationalization.md, source/migration.md, source/plugins.md, themes/meteor/_config.yaml
I left some of the social media links intact because they have not been changed yet.
=> Renamed all changeable occurences of Telescope to Vulcan.

source/internationalization.md
Added hungarian translation to Vulcan.
=> Update internationalization.md - Added Hungarian translation

source/deployment.md
inserted one line with a useful link (i am not affiliated, i just prefer deploying to heroku because i dont understand docker yet)
=> add heroku deployment instructions

source/example-customization.md
Small explanation on how to include assets such as images. Dumb but helpful.
=> Better image adding explanation + example

source/deployment.md
@SachaG 
* Adds [Meteor-now](https://github.com/jkrup/meteor-now) as a deployment option.
=> Adds Meteor-now as a deployment option

source/index.md
Tutorial tutorial. So good we named it twice.
=> Reducing redundancy

source/routing.md
Relates to https://github.com/VulcanJS/Vulcan/pull/1748
=> Added vulcan:routing callback documentation

source/example-movies.md
Components is imported more than once at two places. fixed that
=> Fix duplicate imports in example-movies.md

source/newsletter.md
Updated some older settings for newsletter.
=> Update newsletter settings

source/index.md
I just started checking out Vulcan and thought I'd correct any typos I came across in the documentation.
=> Correct typos in index.md

source/deployment.md
The Meteor Up has a webpage with really great documentation, let's utilise that and direct to it whenever possible. This eliminates some possibilities for outdated information and clarifies where to look for more information if needed.
Added a link to a guide from DigitalOcean on an initial server setup. It might be useful for those who haven't done it before or need a refresher.
Updated the example conf with a configuration that I know works on an Ubuntu 16.04 dev machine to Ubuntu 16.04 server. It should just work though.
Refactored some sentences to remove redundant statements, clarify more specifically
Use some sentences directly from the official MUP docs when I couldn't come up with a proper explanation myself. 
The mup commands have been added to the docs. They are directly copied …
=> Deployment docs update

source/server-queries.md
see also https://github.com/VulcanJS/Vulcan/pull/1995
=> runQuery->runGraphQL

source/example-instagram.md
=> Fix link of GIT repository

source/example-movies.md, source/forms.md
Fixed two errors :
- in the Movies tutorial, fixed error "cannot destructure terms of undefined"
- in the Forms page, fixed wrong component example: `<SmartForm />` replaced by `<Components.SmartForms/>`
=> Small error fixes

source/example-movies.md
Suggest to create a page displaying infos of a single movie
=> Add going further in example-movies

source/forms.md, source/resolvers.md, source/schema-properties.md
This documents adding `submitLabel` to the `SmartForm` component to change the submit label of the form.
=> Submit label

source/forms.md, source/resolvers.md, source/schema-properties.md
Documents refetch on withSingle HOC.
=> Missing documentation additions

source/routing.md
'route' is the object that contains the path
=> change router to route on accessing react router

source/routing.md
Replace `props.router` with `props.history`.
=> Fix manual redirects example

source/storybook.md
Doc for Storybook install
I could not find where the sidebar content is defined, I guess it should go in the "API" part?
=> storybook install

source/database.md
=> Fix grammar in database.md

package-lock.json, package.json
Upgraded to the latest version of hexo and other packages to resolve github vulnerability alerts.
=> Upgrade packages including Hexo 3.8.0

source/cloudinary.md
I just added formats to the settings, so you don't forget it when going through the docs.
=> Update cloudinary settings example

source/example-movies.md
change version in example-movies to fix a bug with User Accounts
=> Fix vulcan varsion in example-movies

source/forms.md
This prop was not documented, but actually implemented.
=> add changeCallback documentation

source/datatable.md
https://github.com/VulcanJS/Vulcan/blob/f5fa18f56dd1948dd950f478113ee6b45734e4bc/packages/vulcan-core/lib/modules/components/Datatable/Datatable.jsx#L304
=> Correct defaultProps explanation
