VulcanJS/vulcan-docs

- source/tutorial-framework.md
Or will throw `ClientError: Created at is required`
> add `optional: true,` to createdAt

- source/packages.md
I found this tip (from the Slackroom) very useful and thought others would too.
> added a note about how to include local packages outside of Vulcan root

- source/internationalization.md
This replaces https://github.com/VulcanJS/Vulcan/pull/1659 - apologies for the confusion.
> added sv-SE

- source/example-movies.md
Using `collectionName: 'movies'` throws error on console: 
``` 
(STDERR) TypeError: Cannot read property 'find' of undefined
(STDERR)     at Object.resolvers.list.resolver (packages/my-package/lib/modules/movies/resolvers.js:8:14)
...
```
Changing it to `collectionName: 'Movies'` fixes the issue.
> Corrected the collection name

- source/example-movies.md
i dont know why. it just didnt run otherwise, and this was the only fix I found by checking `example-simple`
> changing typeName to type, for field resolvers

- source/core-components.md
fixing typo that was closing div tag twice
> fixing typo that was closing div tag twice

- source/forms-upload.md
Preset names have to match between cloudinary & vulcan which can be overlooked and cause a fair bit of head ache.
> Preset names have to match between cloudinary & vulcan

- source/forms-custom.md
Just a couple fixes for syntax errors I spotted while working through the tutorials.
> Forms custom syntax fixes

- source/settings.md
MailGun Note: For username use your Default SMTP Login and for password use Default Password. See screenshot below.
@SachaG I wanted to updated docs for mailgun setup, so it doesnt bring confusion.
If you think that big image is to much, feel free to just link it.
> mailgun settings

- source/example-movies.md
The 404s were due to the change of a data-loading.html page to a resolvers.html page. Found 3 links, changed the 3 to the good ones!
> Fix 404 links in the movies example page

- source/groups-permissions.md
Explanations about the `userId` convention to define ownership of a newly created document.
Also, is that a convention from Meteor itself or from SImple-schema, or is it a pure Vulcan convention?
> Details `userId` and ownership definition

- source/deployment.md
- source/plugins.md
- As mentioned in #63 I added some packages to plugins.md
- deployment.md now explains how to use mup with a two-repo install
> Complete plugins.md and add two-repo tips for mup in deployment.md. Closes issue #63

- source/index.md
Added a short instruction for 'windows users' on where to look for in case they get error during 'npm-install'
> add a short note for windows users

- source/plugins.md
Let me know if I need to modify something.
I am wondering if Vulcan packages should use the same version numbers as its core dependencies 🤔
> Added some packages

- source/groups-permissions.md
I had some issue when playing with `checkAccess` methods. I figured out that to get the correct behaviour when listing data, I also needed to setup a view that "duplicate" the behaviour of checkAccess, but client side. 
This way the `totalCount` can be computed correctly, by counting only the document I actually can see, and it fixes pagination, load more buttons etc.
This is not trivial at first, so I tried to improve the doc on this.
> make the relationship between terms and checkAccess clearer

- source/deployment.md
meteor up uses only global environment variables during the build phase, so they have to be added to your shell prior to running mup setup.
> Update deployment doc

- source/example-movies.md
At line 594, the component name is incorrect, which causes the list of movies not to load if one is copy and pasting from the docs when updating their app.
> Update example-movies.md – Fix MoviesList Component Name.

- source/deployment.md
Hi @Apollinaire and @SachaG - I'm embarrassed. It turns out that `meteor up` does support a local `METEOR_PACKAGE_DIRS`. I was confused because the command is designed to be run from a `.deploy` subdirectory, so I was specifying a relative path to my Vulcan `packages` directory from the `.deploy` directory, not from my project root. So the `meteor build` command, not finding my custom packages, was using a totally different version of Vulcan. Although the change in my original PR is also correct, it's more confusing. I think we should just revert it. Sorry for the confusion.
> Revert "Update deployment doc"

- themes/meteor/layout/layout.ejs
Mobile browsers no longer have a 300ms touch delay. 
REF: https://github.com/ftlabs/fastclick#fastclick
> remove FastClick (no longer needed)

- source/example-movies.md
Whilst working through the movies example I was unable to proceed unless I added document level permissions. I read about the updates here: https://blog.vulcanjs.org/vulcan-js-1-14-filtering-new-apis-fc8efc0027dd
I'm not sure if anything else here should be removed apart from `check`, but it should be enough for a beginner to proceed past this point.
* Added document level permissions
* Removed check in favour of `Users.canCreate`
> Add document-level permissions

- package.json
- themes/meteor/layout/layout.ejs
- themes/meteor/layout/page.ejs
- themes/meteor/source/script/hotkey.js
- themes/meteor/source/script/main.js
- yarn.lock
This uses the npm package [github/hotkey](https://github.com/github/hotkey) . I had to copy & paste the code directly into a file because hexo has no js bundler, so you can't `import X from "package"` like you would with a proper build tool. The S hotkey is something that I always use on the [material-ui docs](https://material-ui.com/), and it's where I've had this idea.
I also found something that was no longer working on the main js script, it triggers an error on the current prod site. It's called [FastClick](https://github.com/ftlabs/fastclick), and it's apparently deprecated now (see note in their readme). I don't know if it has ever worked on the Vulcan doc, but I chose to remove it anyway.
I know this is a two-in-one PR, but the second thing came in at the end and is really not …
> Add "S" hotkey to docs to focus the search input
